origamitower/folktale

src/core/adt/index.js, src/core/adt/show.js, src/data/either/core.js, test/core.adt.es6
I took the code from the 'Either' module and put it into a generic derivation.
Added a representation for the constructor functions (All other values have one, so I think it makes sense).
Using `getOwnPropertyNames` for listing the properties for a given value, because according to [section 14.4.2 from this source](http://exploringjs.com/es6/ch_oop-besides-classes.html) it returns the values in a deterministic order. According to the [MDN docs it doesn't](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames).  In practice both `getOwnPropertyNames` and `Object.keys` work fine. Not so important  since AFAIK names are just for debugging purpose.  We may event consider switching to `keys` to prevent the displaying of non-enumerable …
=> feat: Add show derivation

src/core/adt/index.js, src/core/adt/serialize.js, test/core.adt.es6
This `serialize` derivation adds a `toJSON` method to the instance prototype and a static `fromJSON` function to the ADT constructor. 
`fromJSON` does not use the variant constructors but rather it assumes the listed fields are correct and just copies them.
The methods work recursively: `toJSON` looks for `toJSON` method on each value and leaves it as it is if it does not have one.  `fromJSON` acceps as a second argument an object containing ADT definitions that applies them if the types match. 
Looking forward to hearing your thoughts on this.
=> feat: Add serializations

.eslintrc.json, src/data/either/core.js, src/data/validation/core.js, src/data/validation/fromNullable.js, src/data/validation/index.js, src/helpers/assertFunction.js, test/core.adt.es6, test/data.validation.es6
Done except the functions for converting it to `Either` and (I think also good to have) `Maybe`.
Suggestion: instead of having `fromEither` function, isn't it better if we have `toValidation` method on the Either datatype (and vise-versa). This way you woudn't have to include a module in order to do the conversion, and also seems to me more correct in therms of design.
Looking forward for input on that. 
Also what did you have in mind for the Conversions module in https://github.com/origamitower/folktale/issues/5?
=> Validation

.github/ISSUE_TEMPLATE.md, README.md
This makes the README more direct, and thus easier to find what people want. With this, detailed sections can be moved to other files in the repo or the Wiki, depending on whether they're dependent on some version of Folktale or not.
=> Simplifies and organises README

.npmignore, CONTRIBUTORS, package.json
Fixes #32. I looked at the `Makefile` to make sure I wasn't missing anything—essentially this change says "include only  what is in this array when publishing to npm".
Some files are always included and don't need to be specified, and some are always ignored. See [here](https://docs.npmjs.com/files/package.json#files) for more info.
If I missed anything, let me know!
=> Replace `npmignore` with whitelist

package.json, src/core/adt/setoid.js, src/core/fantasy-land/core/ap.js, src/data/either/core.js, src/data/maybe/core.js, src/data/validation/core.js, src/helpers/provide-fantasy-land-aliases.js
Following the work on #37, and addressing #39, this patch moves the Fantasy Land interface to aliases of the actual methods in Folktale structures. The new `provide-fantasy-land-aliases` module takes care of handling the aliases automatically, so this allows us to diverge our public API from Fantasy Land interfaces as well (avoiding issues like this recent PR https://github.com/fantasyland/fantasy-land/pull/145), as long as we can map it to the interfaces. It also allows us to choose better names (e.g.: `.apply()` instead of `.ap()`).
Closes #39.
=> Refactor for some fantasy-land stuff

src/data/maybe/core.js
previously it derive setoid twice. This commit remove one of them.
=> (fix maybe) fix double setoid derive

docs/api/en/folktale.src.core.lambda.curry.curry.html, docs/source/en/core/lambda/curry.md
Corrects the lack of newline between ordered list items
Fixes #63
=> (fix doc) correctly formats curry documentation

.gitignore, Makefile, docs/.babelrc, documentation.js, test/.babelrc, test/specs-src/core.object.js, test/specs-src/data.result.js, test/specs-src/data.validation.js
This means that browser bundles won't have metamagical annotations
anymore, so they're much smaller (244K → 52K, 4.7x smaller).
This fixes #79
=> Generates annotated files only for tests/docs

src/data/maybe/index.js, src/data/result/index.js
.hasInstance uses the type in the context object to determine if the value is an instance or not. This was broken when the Maybe and Result modules stopped exporting that (among other) properties.
=> (fix) Fixes hasInstance for Maybe/Result

docs/api/en/folktale.data.task.fromnodeback.html, docs/api/en/folktale.data.task.html, docs/source/en/data/task/from-nodeback.md, src/data/task/index.js
Task.fromNodeback was missing its type annotation, and annotation for `folktale.data.task...` was `folktale.data.result...` by accident.
=> (fix task docs) Adds missing type and fixes copy/paste typo

docs/source/en/data/conversions/future-to-promise.md, docs/source/en/data/conversions/promise-to-future.md, docs/source/en/data/future/fromPromise.md, docs/source/en/data/future/toPromise.md, src/data/conversions/future-to-promise.js, src/data/conversions/index.js, src/data/conversions/promise-to-future.js, src/data/future/_future.js, src/data/future/index.js, test/specs-src/data.future.es6
=> Promise <-> Future conversion

README.md, docs/source/en/data/task/index.md, docs/source/en/data/task/task-execution/cancel.md, docs/source/en/data/task/task.md, docs/source/en/data/task/task/and.md, docs/source/en/data/task/task/or.md, docs/source/en/data/task/wait-any.md, package.json, src/data/task/_task.js, src/data/task/index.js, src/data/task/task.js, test/karma-sauce.js, test/specs-src/data.task.js
Previously the Task API had separate functions for cleanup and for handling cancellation. These functions were defined outside of the Task computation, which means Task had to return references to the allocated resources so those functions could do their jobs.
This obviously didn't work for places where resolution happened synchronously, as they'd have to be called before those references were returned. Calling them asynchronously meant that race conditions on when exactly "cancellation/cleanup" and pending resolutions happen were possible. Which is not a good thing.
Merely making all resolutions asynchronous wouldn't really fix the issue, although it would have made it less likely to happen.
Anyway, I decided to have the computation itself add handlers for cancellation and cleanup …
=> Makes race conditions harder with the Task API

src/data/maybe/index.js, src/data/maybe/maybe.js, test/specs-src/data.maybe.js
Implements semigroup and monoid for Maybe.
=> Implements semigroup and monoid for Maybe.

packages/base/CONTRIBUTORS, packages/base/source/concurrency/task/wait-all.js, test/source/specs/base/concurrency/task.js
This change removes a guard on the length of the list passed to `Task.waitAll`.
Let me know if there are any other changes needed to make this pull request acceptable.
Thanks!
Closes #130
=> Allow Task.waitAll to take an empty list of tasks

packages/base/source/concurrency/task/do.js, packages/base/source/concurrency/task/index.js, test/source/specs/base/concurrency/task.js
As per issue #111.
I've seen it's scheduled for `post-2.0` but I had the code lying around and I love my (syntactic) sugar.
It can be used like this:
```
Task.do(function *() {
const a = yield delay(10); 
const b = yield delay(11); 
const c = yield Task.of(5);
return Task.of(a + b + c + 4);
})
```
Right now all the yielded / returned values need to be an instance of Task and behave like Haskell's bind, while in JavaScript (async/await, coroutines) values get promisified if they're not Promises.
I personally think it's confusing to promisify things implicitly and caused a few misunderstanding while teaching newcomers.
What do you think about it?
EDIT: I forgot to say, I'm not sure I followed the right convention for the type annotation, so that may need some fixing
Thanks
=> Adds Task.do

annotations/source/en/concurrency/future/future/or-else.md, packages/base/source/concurrency/future/_future.js
=> Renames Future.recover -> Future.orElse (#136)

annotations/source/en/validation/index.md
I was reading through the `Validation` documentation and noticed this little typo(?). I'm correct in assuming that the validators should return their `value` property in a `Success`, not the `field`, right?
~~Sorry about the extra `\n` at EOF. I made this patch with the Github editor and it looks like it just tacked that on. I can kill it if y'all prefer.~~ Making the change in the markdown file made this comment moot.
=> Fix Success value in `notEmpty` validation example

docs/_docs/v2.0.0/migrating/from-data.task.md
=> Fixes migration docs for Task

README.md, docs/_docs/v2.0.0/download.md
=> Adds note on shims for older platforms (#155)

packages/base/package.json, packages/base/source/concurrency/task/_task-execution.js, packages/base/source/concurrency/task/_task.js, test/source/browser/browser-tests.js, test/source/specs/base/concurrency/regression/task-cancellation-174.js
Tasks are still experimental and they're developed in a fairly adhoc manner. This results in a lot of edge cases that are hard to cover under concurrent execution (races are always a pain), and makes it harder for people to reason about their code. #174 and #153 are examples of that.
The current PR includes an initial mitigation  of #174 until Tasks are formalised. The common problems of cancelling tasks are solved by this, but there's no way of knowing if other edge cases exist without formalising.
You can try out these changes by installing version `2.2.0-alpha1`, or just grab the `@next` branch: 
npm i folktale@next
=> Tasks, Concurrency, and Cancellation

packages/base/source/adt/union/derivations/debug-representation.js, test/source/specs/base/adt/union.js
Previously JSON.stringify was used for representing numbers, but that doesn't work with special IEEE754 values like NaN and Infinity.
This fixes #191
=> Fixes debug representation for numbers

annotations/source/en/validation/chain.md, packages/base/source/validation/chain.js, packages/base/source/validation/index.js, test/source/specs/base/validation/validation.js
This allows manipulating Success in a simpler way than the full-blown matchWith without interfering with the Applicative instance. Addresses #175
=> Adds a chain function to Validation

.travis.yml, build.frp, package-lock.json, packages/base/source/adt/union/union.js, test/source/specs/base/adt/union.js, test/source/specs/base/core/object.js
Previously we exposed the original initialiser as the `constructor` property. This caused problems with ES2015 additions, such as shorthand methods and arrow functions, which are not constructable.
Addresses #190
=> Fixes union variants with non-constructable initialisers

packages/base/source/concurrency/future/_deferred.js
When we try to settle a deferred that's already settled we get a message saying that it's not possible to move to the new state, because the current state is not "pending"... except it described the new state where it should describe the old one. Ooops!
This addresses part of the last comment in #153
=> Fixes deferred state message.

packages/base/source/conversions/nodeback-to-task.js, test/source/specs/base/concurrency/task.js
Fixes #215 
Added a test by following the given principle from the doc:
> tests should fail before applying your change, and pass after applying your change.
=> Fixes async task from node error
